_target_: contrail_segmentation.models.pretrained_unet.PretrainedUNET

lr: 1e-4 
wd: 1e-2
beta1: 0.9
beta2: 0.999
threshold: 0.3
dice_weight: 0.5
focal_weight: 0.5
pos_weight: 20

encoder_class:
  _partial_: true
  _target_: segmentation_models_pytorch.Unet
  encoder_name: resnet50
  encoder_weights: imagenet
  in_channels: 24
  classes: 1

dice_loss: 
  _partial_: true
  _target_: segmentation_models_pytorch.losses.DiceLoss
  from_logits: true
  mode: binary

bce_loss: 
  _partial_: true
  _target_: torch.nn.BCEWithLogitsLoss
